int inteiro = 30;
//Console.WriteLine (inteiro);
float f = 1.2f;
//Console.WriteLine (f);
decimal d = 1.333m;
//Console.WriteLine (d);
double d2 = 2.55;
//Console.WriteLine (d2);
char c = 'a';
//Console.WriteLine (c);
string s = "A Twitch tá de sacanagem";
//Console.WriteLine (s);
bool b = true;
//Console.WriteLine (b);
//Console.WriteLine (inteiro + f.ToString() + d + d2 + c + s + b);
Console.WriteLine (inteiro.GetType());
Console.WriteLine (f.GetType());
Console.WriteLine (d.GetType());
Console.WriteLine (d2.GetType());
Console.WriteLine (c.GetType());
Console.WriteLine (s.GetType());
Console.WriteLine (b.GetType());
